# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

# -- general conf
general {
    colors = true
    interval = 7
}

# -- display order 
order += "cpu_temperature 0"
order += "cpu_usage"
order += "memory"
order += "path_exists VPN"
order += "wireless _first_"
order += "ethernet _first_"
order += "disk /"
order += "tztime local"
order += "volume master"

# -- paths 

# -- cpu 
#cpu_temperature 0 {
    #format = "%degrees °C"
    #path = "/sys/class/hwmon/hwmon1/temp1_input"
    #max_threshold = 45
#}
cpu_usage {
    format = "%usage"
    format_above_degraded_threshold = "%usage"
    max_threshold = "80"
    degraded_threshold = "25"
}

# -- internet
path_exists VPN {
    format = "{vpn}"
    format_down=""
    path = "/proc/sys/net/ipv4/conf/proton0"
}
wireless _first_ {
    format_up = "(%quality )"
    format_down = "( - )"
}
ethernet _first_ {
    format_up = "[ %speed ]"
    format_down = "[ - ]"
}

# -- memory, storage usage, others
disk "/" {
    format = "%used (%percentage_used)"
}
memory {
    format = "%used (%percentage_used)"
    format_degraded = "%used (%percentage_used X %percentage_free)"
    threshold_degraded = "70%"
    threshold_critical = "20%"
}
volume master {
    format = "♪:%volume"
    format_muted = "♪X:%volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

# -- time and date
tztime local {
    format = "%Y-%m-%d %H:%M:%S"
}
